language: node_js

node_js:
  - lts/* 

script:
  - cd ./greeting-service
  - npm install --silent
  - npm run ci
  - cd ..
  - cd cute-name-service
  - npm install --silent
  - npm run ci

branches:
  only:
    - main
    - /^greenkeeper/.*$/
